### PR TITLE
Try adding uri safe

### PR DESCRIPTION
**Pull request by diansf**
Hi @Altivi is this okay to add support for uri safe ?

similar on https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.js#L93

thank you

### CODE REVIEW

**Comment by altivi** [comment]
LGTM, thanks @diansf

**Comment by diansf** [comment]
Thank you @Altivi

**Comment by chrisalbrecht** [comment]
@Altivi Can you release/publish an updated version of the gem with this change?

**Comment by altivi** [comment]
@diansf @chrisalbrecht New version has been released. Apologies for the significant delay.

**Pull request merged**
